// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmcBa9N5UqiprkE6P1UcpjCZtKIP0zjJc',
    appId: '1:1094072156627:web:b3ba42553edd970606ef26',
    messagingSenderId: '1094072156627',
    projectId: 'drift-4ea4d',
    authDomain: 'drift-4ea4d.firebaseapp.com',
    storageBucket: 'drift-4ea4d.appspot.com',
    measurementId: 'G-CH0BVNE678',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE0KPzLI8QeLE8uF17LDifdRtEiCFfFsI',
    appId: '1:1094072156627:android:456c9d50409c499206ef26',
    messagingSenderId: '1094072156627',
    projectId: 'drift-4ea4d',
    storageBucket: 'drift-4ea4d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1kT_rQezmwnJMLnR9fY8cHzaWc7BzMew',
    appId: '1:1094072156627:ios:a97b1aca6c2666b206ef26',
    messagingSenderId: '1094072156627',
    projectId: 'drift-4ea4d',
    storageBucket: 'drift-4ea4d.appspot.com',
    iosBundleId: 'com.example.drift',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1kT_rQezmwnJMLnR9fY8cHzaWc7BzMew',
    appId: '1:1094072156627:ios:02b9ac73dc82189a06ef26',
    messagingSenderId: '1094072156627',
    projectId: 'drift-4ea4d',
    storageBucket: 'drift-4ea4d.appspot.com',
    iosBundleId: 'com.example.drift.RunnerTests',
  );
}
